---
- name: Setup Jenkins Server
  hosts: jenkins_server
  become: yes
  gather_facts: True
  vars:
    ansible_python_interpreter: /usr/bin/python3
    userId: 1000
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install required Docker prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - jq
        state: present
    - name: Create /etc/apt/keyrings if it does not exist
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true
    - name: Get Ubuntu codename
      ansible.builtin.shell: |
        . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
      register: ubuntu_codename
    - name: Get architecture
      ansible.builtin.shell: dpkg --print-architecture
      register: architecture

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
        state: present

    - name: Update apt cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Engine
      ansible.builtin.apt:
        name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin
        state: present

    - name: Ensure Docker service is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Make sure ubuntu user is added to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker

    - name: Create jenkins network
      community.docker.docker_network:
        name: jenkins
        state: present
    
    - name: Run alpine/socat container to forward traffic from Jenkins to Docker 
      community.docker.docker_container:
        name: socat
        image: alpine/socat
        state: started
        restart_policy: always
        detach: yes
        networks:
          - name: jenkins
        published_ports:
          - "2376:2375"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
      ignore_errors: yes
      # #
      # ansible.builtin.shell: |
      #   docker run --name socat -d --restart=always -p 127.0.0.1:2376:2375 --network jenkins -v /var/run/docker.sock:/var/run/docker.sock alpine/socat tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
      # ignore_errors: yes

    - name: Ensure /var/jenkins directory exists
      file:
        path: /var/jenkins
        state: directory
        owner: ubuntu
    
    - name: Move Jenkins Dockerfile to Server
      ansible.builtin.copy:
        src: /ftp/projects/cicd/docker/Dockerfile
        dest: /var/jenkins/Dockerfile
    
    - name: Build Jenkins Docker Image
      ansible.builtin.shell: |
        docker build -t myjenkins-blueocean:2.528.1-1 /var/jenkins
    
    - name: Run Jenkins BlueOcean container 
      community.docker.docker_container:
        name: jenkins-blueocean
        image: myjenkins-blueocean:2.528.1-1
        state: started
        restart_policy: on-failure
        detach: yes
        networks:
          - name: jenkins
        env:
          DOCKER_HOST: tcp://docker:2376
          DOCKER_CERT_PATH: /certs/client
          DOCKER_TLS_VERIFY: '1'
        published_ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins-data:/var/jenkins_home
          - jenkins-docker-certs:/certs/client:ro
      ignore_errors: yes
      # ansible.builtin.shell: |
      #   docker run --name jenkins-blueocean --restart=on-failure --detach \
      #   --network jenkins --env DOCKER_HOST=tcp://docker:2376 \
      #   --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1 \
      #   --publish 8080:8080 --publish 50000:50000 \
      #   --volume jenkins-data:/var/jenkins_home \
      #   --volume jenkins-docker-certs:/certs/client:ro \
      #   myjenkins-blueocean:2.528.1-1
      # ignore_errors: yes

    - name: Get socat container IP address
      ansible.builtin.shell: |
        docker inspect socat | jq -r .[].NetworkSettings.Networks.jenkins.IPAddress
      register: socat_ip
    
    - name: Print socat container IP address
      ansible.builtin.debug:
        msg: "Socat container IP address is {{ socat_ip.stdout }}"
    
    - name: Wait for the Jenkins container to be up
      ansible.builtin.wait_for:
        host: localhost
        port: 8080
        timeout: 300
        state: started

    - name: Display Jenkins initial admin password
      ansible.builtin.shell: |
        docker exec jenkins-blueocean cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_admin_password
    - name: Show Jenkins initial admin password
      ansible.builtin.debug:
        msg: "Jenkins initial admin password is {{ jenkins_admin_password.stdout }}"
    # - name: Update apt cache

    # - name: Install fontconfig package
    #   ansible.builtin.apt:
    #     name: fontconfig
    #     state: present
    # - name: Install Java
    #   ansible.builtin.apt:
    #     name: openjdk-21-jre
    #     state: present
    # - name: Create /etc/apt/keyrings if it does not exist
    #   file:
    #     path: /etc/apt/keyrings
    #     state: directory
    #     mode: '0755'
    # - name: Add Jenkins GPG key
    #   ansible.builtin.get_url:
    #     url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    #     dest: /etc/apt/keyrings/jenkins-keyring.asc
    #     mode: '0644'
    #     force: true
    # - name: Add Jenkins repository
    #   ansible.builtin.apt_repository:
    #     repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    #     state: present
    # - name: Update apt cache after adding Jenkins repo
    #   ansible.builtin.apt:
    #     update_cache: yes
    # - name: Install Jenkins
    #   ansible.builtin.apt:
    #     name: jenkins
    #     state: present
    # - name: Ensure Jenkins is started and enabled
    #   ansible.builtin.service:
    #     name: jenkins
    #     state: started
    #     enabled: yes
    # - name: Get initial admin password
    #   ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
    #   register: jenkins_admin_password
    # - name: Display Jenkins initial admin password
    #   ansible.builtin.debug:
    #     msg: "Jenkins initial admin password is {{ jenkins_admin_password.stdout }}"

# - name: Configure Jenkins Permanent Agent
#   hosts: jenkins_agent
#   gather_facts: True
#   become: yes
#   tasks:
#     - name: Create Jenkins agent directory
#       file:
#         path: /var/jenkins
#         state: directory
#         owner: ubuntu
#         group: ubuntu
#     - name: Update apt cache
#       ansible.builtin.apt:
#         update_cache: yes
#     - name: Install fontconfig package
#       ansible.builtin.apt:
#         name: fontconfig
#         state: present
#     - name: Install Java
#       ansible.builtin.apt:
#         name: openjdk-21-jre
#         state: present
#     - name: Install nginx
#       ansible.builtin.apt:
#         name: nginx
#         state: present
#     - name: Ensure nginx is started and enabled
#       ansible.builtin.service:
#         name: nginx
#         state: started
#         enabled: yes